-- ----------- Tables Admin Level --------------
DROP TABLE IF EXISTS `customer`;
CREATE TABLE `customer` (
    `customer_no` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `allowed_cidr` VARCHAR(250) DEFAULT NULL,
    `rateLimitMaxRequest` BIGINT DEFAULT NULL,
    `rateLimitMaxRequestWindow` BIGINT DEFAULT NULL,
    `customer_username` VARCHAR(100) NOT NULL,
    `customer_password_hash` VARCHAR(150) NOT NULL,
    `customer_user_token` VARCHAR(100) NULL DEFAULT NULL,
    `customer_user_token_ts` DATETIME NULL DEFAULT NULL,
    `customer_general_information` VARCHAR(150) NULL DEFAULT NULL,
    `sub_domain` VARCHAR(15) DEFAULT NULL,
    `api_domain` VARCHAR(250) DEFAULT NULL,
    `open_api_domain` VARCHAR(250) DEFAULT NULL,
    `master_db_server_type` VARCHAR(250) NOT NULL,
    `master_db_server_hostname` VARCHAR(250) NOT NULL,
    `master_db_server_port` VARCHAR(250) NOT NULL,
    `master_db_server_username` VARCHAR(250) NOT NULL,
    `master_db_server_password` VARCHAR(250) NOT NULL,
    `master_db_server_db` VARCHAR(250) NOT NULL,
    `master_db_server_query_placeholder` VARCHAR(250) NOT NULL,
    `slave_db_server_type` VARCHAR(250) NOT NULL,
    `slave_db_server_hostname` VARCHAR(250) NOT NULL,
    `slave_db_server_port` VARCHAR(250) NOT NULL,
    `slave_db_server_username` VARCHAR(250) NOT NULL,
    `slave_db_server_password` VARCHAR(250) NOT NULL,
    `slave_db_server_db` VARCHAR(250) NOT NULL,
    `slave_db_server_query_placeholder` VARCHAR(250) NOT NULL,
    `usersTable` VARCHAR(250) NOT NULL,
    `master_cache_server_type` VARCHAR(250) NOT NULL,
    `master_cache_server_hostname` VARCHAR(250) NOT NULL,
    `master_cache_server_port` VARCHAR(250) NOT NULL,
    `master_cache_server_username` VARCHAR(250) NOT NULL,
    `master_cache_server_password` VARCHAR(250) NOT NULL,
    `master_cache_server_db` VARCHAR(250) NOT NULL,
    `master_cache_server_table` VARCHAR(250) NOT NULL,
    `slave_cache_server_type` VARCHAR(250) NOT NULL,
    `slave_cache_server_hostname` VARCHAR(250) NOT NULL,
    `slave_cache_server_port` VARCHAR(250) NOT NULL,
    `slave_cache_server_username` VARCHAR(250) NOT NULL,
    `slave_cache_server_password` VARCHAR(250) NOT NULL,
    `slave_cache_server_db` VARCHAR(250) NOT NULL,
    `slave_cache_server_table` VARCHAR(250) NOT NULL,
    `customer_created_by` BIGINT DEFAULT NULL,
    `customer_created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `customer_approved_by` BIGINT DEFAULT NULL,
    `customer_approved_on` TIMESTAMP NULL DEFAULT NULL,
    `customer_updated_by` BIGINT DEFAULT NULL,
    `customer_updated_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `customer_is_editable` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_is_approved` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_is_disabled` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_is_deleted` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    PRIMARY KEY (`customer_no`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `customer_contact`;
CREATE TABLE `customer_contact` (
    `customer_contact_no` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_no` BIGINT NOT NULL,
    `customer_contact_name` VARCHAR(100) NOT NULL,
    `customer_contact_person` VARCHAR(100) NOT NULL,
    `customer_contact_firm` VARCHAR(100) NOT NULL,
    `customer_contact_department` VARCHAR(100) NOT NULL,
    `customer_contact_email_address` VARCHAR(100) NOT NULL,
    `customer_contact_phone` VARCHAR(100) NOT NULL,
    `customer_contact_fax` VARCHAR(100) NOT NULL,
    `customer_contact_mailing_address` VARCHAR(100) NOT NULL,
    `customer_contact_city` VARCHAR(100) NOT NULL,
    `customer_contact_state` VARCHAR(100) NOT NULL,
    `customer_contact_zip` VARCHAR(100) NOT NULL,
    `customer_contact_country` VARCHAR(100) NOT NULL,
    `customer_contact_general_information` VARCHAR(150) NULL DEFAULT NULL,
    `customer_contact_created_by` BIGINT DEFAULT NULL,
    `customer_contact_created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `customer_contact_approved_by` BIGINT DEFAULT NULL,
    `customer_contact_approved_on` TIMESTAMP NULL DEFAULT NULL,
    `customer_contact_updated_by` BIGINT DEFAULT NULL,
    `customer_contact_updated_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `customer_contact_is_editable` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_contact_is_approved` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_contact_is_disabled` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_contact_is_deleted` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    PRIMARY KEY (`customer_contact_no`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `customer_group`;
CREATE TABLE `customer_group` (
    `customer_group_no` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `allowed_cidr` VARCHAR(250) DEFAULT NULL,
    `rateLimitMaxRequest` BIGINT DEFAULT NULL,
    `rateLimitMaxRequestWindow` BIGINT DEFAULT NULL,
    `customer_group_name` VARCHAR(100) NOT NULL,
    `customer_group_general_information` VARCHAR(250) DEFAULT NULL,
    `customer_group_created_by` BIGINT DEFAULT NULL,
    `customer_group_created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `customer_group_approved_by` BIGINT DEFAULT NULL,
    `customer_group_approved_on` TIMESTAMP NULL DEFAULT NULL,
    `customer_group_updated_by` BIGINT DEFAULT NULL,
    `customer_group_updated_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `customer_group_is_editable` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_group_is_approved` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_group_is_disabled` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `customer_group_is_deleted` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    PRIMARY KEY (`customer_group_no`)
) ENGINE = InnoDB;

DROP TABLE IF EXISTS `customer_group_link`;
CREATE TABLE `customer_group_link` (
    `sr_no` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `customer_no` BIGINT NOT NULL,
    `customer_group_no` BIGINT NOT NULL,
    `created_by` BIGINT DEFAULT NULL,
    `created_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `approved_by` BIGINT DEFAULT NULL,
    `approved_on` TIMESTAMP NULL DEFAULT NULL,
    `updated_by` BIGINT DEFAULT NULL,
    `updated_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `is_editable` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `is_approved` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `is_disabled` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    `is_deleted` ENUM('Yes', 'No') NOT NULL DEFAULT 'No',
    PRIMARY KEY (`sr_no`)
) ENGINE = InnoDB;
-- ----------- Tables Admin Level --------------
